name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies (if requirements.txt)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests if pytest available
        run: |
          if command -v pytest >/dev/null 2>&1; then
            pytest -q --maxfail=1 || exit 1
          else
            echo "pytest not found, skipping tests"
          fi

      - name: Run flake8 if available
        run: |
          if command -v flake8 >/dev/null 2>&1; then
            flake8 || echo "flake8 reported issues"
          else
            echo "flake8 not installed, skipping lint"
          fi
